"""Initial migration

Revision ID: 2bbb20223c8e
Revises:
Create Date: 2023-04-15 09:20:12.088870

"""

# revision identifiers, used by Alembic.
revision = "2bbb20223c8e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
